export const BUDGET = 'BUDGET'
export const FITNESS = 'FITNESS'
export const INVENTORY = 'INVENTORY'
export const RECIPES = 'RECIPES'
export const REPLENISHABLES = 'REPLENISHABLES'
export const SERVER_URL = 'http://joelle.local:3000'
