export const BUDGET = 'BUDGET'
export const COLLECTIONS = 'COLLECTIONS'
export const FITNESS = 'FITNESS'
export const INVENTORY = 'INVENTORY'
export const LINKS = 'LINKS'
export const RECIPES = 'RECIPES'
export const REPLENISHABLES = 'REPLENISHABLES'
export const SERVER_URL = 'http://joelle.local:3000'
